# Jekyll Configuration for GitHub Pages Example
title: "GitHub Pages with Jekyll"
description: "A demonstration of Jekyll static site generator with GitHub Pages"
author: "Richard Borges"
email: "richard@example.com"
baseurl: "/github-pages-examples/jekyll-site"
url: "https://richardborgesdev.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:name/
  projects:
    output: true
    permalink: /:collection/:name/

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Richard Borges"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Social links
github_username: richardborgesdev
linkedin_username: richardborgesdev

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _pages

# Pagination
paginate: 5
paginate_path: "/page:num/"

# SEO settings
lang: en
timezone: America/Sao_Paulo