name: Build and Deploy Custom Site

on:
  push:
    branches: ["main", "master"]
    paths: 
      - "github-pages-examples/custom-actions/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "custom-pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './github-pages-examples/custom-actions/package-lock.json'
          
      - name: Install dependencies
        run: |
          cd github-pages-examples/custom-actions
          npm ci
          
      - name: Build site
        run: |
          cd github-pages-examples/custom-actions
          npm run build
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './github-pages-examples/custom-actions/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4