name: Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: richardborgesdev
          committer_branch: main
          config_timezone: America/Sao_Paulo
          base: header, activity, community, repositories
          base_indepth: yes
          plugin_languages: yes
          plugin_languages_limit: 8
